/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommentsCommentIdRouteImport } from './routes/comments/$commentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsCommentIdRoute = CommentsCommentIdRouteImport.update({
  id: '/comments/$commentId',
  path: '/comments/$commentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comments/$commentId': typeof CommentsCommentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comments/$commentId': typeof CommentsCommentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comments/$commentId': typeof CommentsCommentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comments/$commentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comments/$commentId'
  id: '__root__' | '/' | '/comments/$commentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommentsCommentIdRoute: typeof CommentsCommentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments/$commentId': {
      id: '/comments/$commentId'
      path: '/comments/$commentId'
      fullPath: '/comments/$commentId'
      preLoaderRoute: typeof CommentsCommentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommentsCommentIdRoute: CommentsCommentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
